### ISSUE TITLE
Gotta Go Slow

### ISSUE THREAD

**Issue by ValerieTheBun** [gravypod/AllAdmin#3]
I'm encountering an issue where breaking blocks on the server faster than about 2 blocks/s kicks players from the server. 

The console prints out with this: http://pastebin.com/dnHF3Pzr
It looks like the event handler isn't handling fast enough.

I've tested this without AllAdmin, and have been unable to replicate the issue. My server is running Agrarian Skies 2.1.9, with this mod being the only one added.

**Comment by gravypod** [comment]
If I where you I would use http://minecraft.curseforge.com/mc-mods/74735-forge-essentials. The plugin is much better and I rarely update this.

**Comment by ValerieTheBun** [comment]
Ah, I was not aware that FE was still in development. Thank you for taking the time to respond!

**Comment by gravypod** [comment]
No problem @tristan1301, have a nice day.
